### ISSUE TITLE
Unnecessary and rude image included in /data/misc folder

### ISSUE THREAD

**Issue by Honno** [red-eclipse/data#2]
A certain largeandincharge.png image can be found in the misc folder and I for one find it completely obscene!

In all seriousness, shouldn't it be removed if we want RE to reach greater heights or something?

Thanks to MaxPayne for pointing this out.

**Comment by shirepirate** [comment]
i agree that it seems out of place even as a joke / easter egg, there's plenty of other crap that could be added instead of something obscene. i asked to remove it before but was told not to.

**Comment by ZeroKnight** [comment]
Haha good times. I can remember the day that myself, @qreeves @Wazubaba and Gingerbear were sitting in Teamspeak giggling our asses off as Wazu found the image and Quin added it as an easter egg. Kind of hilarious it took this long for it to be generally noticed.

As a note, while it has always been in the repo itself, the Makefile *does* delete it when making a release... so there's that :p

**Comment by Evropi** [comment]
Really now, Honno. :stuck_out_tongue:

The game is not for children anyway, so I say hey, why not keep it? Red Eclipse isn't a soulless corporate entity and can have a bit of fun like this. One of the default voice commands is "suck it" for Christ's sake.

**Comment by qreeves** [comment]
As I have explained in the past, this is sort of thing is classed as *parody* as it is not derogatory to any gender/race/sexual orientation. As @ZeroKnight points out, the file is removed for official release builds, so it is more of an in-development-community joke more than anything.

Try it: `/dominatetex textures/misc/largeandincharge; dominatedtex textures/misc/largeandincharge`

**Comment by Honno** [comment]
Haha ok, I just thought you guys might of missed it :p
