### ISSUE TITLE
Escape: Checkpoint angles and sound errors

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/data#20]
Just to keep track of these issues on the race map *escape*.
http://redeclipse.net/forum/viewtopic.php?f=5&t=354&start=175#p5605

**Comment by bonifarz** [comment]
It would be nice to get this fixed for 0.5.2 - at least the checkpoints angles, as posted on the forums. Maybe Goku can have another look at his map and redo the placing of sound ents.

**Comment by shirepirate** [comment]
you should make an effort to contact him if you aren't planning on doing it yourself (which would be perfectly reasonable too)
