### ISSUE TITLE
New zapper sounds

### ISSUE THREAD

**Issue by Calinou** [red-eclipse/data#21]
They might need a volume decrease.
*License: CC0 1.0*

https://dl.dropboxusercontent.com/u/82342922/downloads/red-eclipse/zapper-sounds.zip

**Comment by qreeves** [comment]
Is there a reason you're not doing proper pull requests? Also, what's wrong with the current sound?

**Comment by shirepirate** [comment]
this sounds more like a laser gun on a ship, not sure if it really fits the weapon. i just can't hear the electricity in this sound effect, at least not nearly as much so as the current effect.

**Comment by Calinou** [comment]
> Also, what's wrong with the current sound?

The current sound is too quiet compared to the shock effect it delivers.
